#Sum and Average
#numbers = [10, 20, 30, 40, 50]
#total = sum(numbers)
#avg = total / len(numbers)
#print("Sum:", total)
#print("Average:", avg)

#Remove duplicates
#num_value = [1,1,2,2,3,3,34,43]
#final_value = list(set(num_value))
#print(final_value)

#Reverse a list 
# Example: List of numbers
numbers = [10, 20, 30, 40]

# Accessing elements
print("First number:", numbers[0])

# Adding a new number
numbers.append(50)
print("Updated list:", numbers)

# Looping through list
for num in numbers:
    print("Number:", num)




